[package]
name = "rules_utils"
version = "0.1.0"

[lib]
name = "rules_utils"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.1.0-rc2"
